### PR TITLE
Support mecanum drive

### PR DESCRIPTION
**Pull request by mqcmd196**
Supporting mecanum drive in kxr with wheels. Cc: @a-ichikura

### CODE REVIEW

**Comment by mqcmd196** [comment]
TODO: send mecanum drive controller's PR to https://github.com/ros-controls/ros_controllers

**Comment by mqcmd196** [comment]
@iory 
I confirmed that the patch works on @a-ichikura 's robot. 
BTW, this PR's `cmd_vel` namespace is `ridgeback_control`, and it should be fixed. What is the appropriate name? I think the `/cmd_vel` is better

**Comment by iory** [comment]
Could you upload video?
`/cmd_vel` is fine.

**Comment by mqcmd196** [comment]
> TODO: send mecanum drive controller's PR to https://github.com/ros-controls/ros_controllers

update: https://github.com/ros-controls/ros_controllers/pull/558 There are some patches, but not released

**Comment by mqcmd196** [comment]
Port https://github.com/iory/robot-programming/blob/jedy/jedy/jedy_description/config/jedy_servo_config.yaml to https://github.com/iory/rcb4/blob/efe38055575d7fc9868efec3c3b57c249738bd53/ros/kxr_models/config/kxrmw4a6h2m_servo_config.yaml

**Comment by mqcmd196** [comment]
I noticed the PR doesn't work with `roslaunch kxr_controller kxr_controller_for_wheel.launch` .  It had better to send PR to https://github.com/iory/robot-programming/tree/jedy.

I'm not sure the difference between Jedy and kxrmw4a6h2m ...

**Pull request closed without merging**
