### PR TITLE
Enable servo temperature

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Looks good to me.

First 4 elements: KRS6104
Next 3 elements: KRS3302（青サーボ）
Last element: KRS3304（赤サーボ）

```
In [1]: interface.read_servo_temperature()
Out[1]: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [2]: interface.switch_reading_servo_temperature(True)
Out[2]: array([252,   1], dtype=uint8)

In [3]: interface.read_servo_temperature()
Out[3]: array([111, 111, 111, 111,   0,   0,   0, 110], dtype=uint8)
```

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
FYI

https://kondo-robot.com/w/wp-content/uploads/ICS3.5_SoftwareManual_1_1.pdf

Screenshot 2024-11-01 21:38:39

Screenshot 2024-11-01 21:39:52

**Comment by 708yamaguchi** [comment]
Looks good to me.

Servo off
```
In [2]: interface.read_servo_temperature()
Out[2]: 
array([37.5     , 37.5     , 37.5     , 37.5     ,  0.      ,  0.      ,
        0.      , 39.166668], dtype=float32)

In [4]: interface.read_servo_current()
Out[4]: array([0., 0., 0., 0., 0., 0., 0., 0.])

```

Servo on 
```
In [6]: interface.read_servo_temperature()
Out[6]: 
array([38.333336, 38.333336, 38.333336, 38.333336,  0.      ,  0.      ,
        0.      , 40.833336], dtype=float32)

In [22]: interface.read_servo_current()
Out[22]: array([ 0. ,  0.2,  0. , -0. , -0. , -0. , -0. ,  0.1])
```

**Comment by 708yamaguchi** [comment]
`read_current_limit` should return interpolated value?

```
In [73]: interpolate_currents(interface.read_current_limit())
Out[73]: 
array([3.10000002, 3.10000002, 3.10000002, 3.10000002, 1.5       ,
       1.5       , 1.5       , 0.        ])

In [74]: interpolate_or_extrapolate_temperatures(interface.read_temperature_limit())
Out[74]: 
array([108.82352978, 108.82352978, 108.82352978, 108.82352978,
       114.70588297, 114.70588297, 114.70588297,  95.88235277])
```

**Comment by iory** [comment]
```
In [1]: interface.send_current_limit(4)
Out[1]: b'\x12\x06'

In [2]: interface.read_current_limit()
Out[2]:
array([4.00000003, 4.00000003, 4.00000003, 4.00000003, 4.00000003,
       4.00000003, 4.00000003, 4.00000003, 4.00000003, 4.00000003,
       4.00000003, 4.00000003, 4.00000003, 4.00000003, 4.00000003,
       4.00000003, 4.00000003, 4.00000003])

In [3]: interface.send_current_limit(3)
Out[3]: b'\x12\x06'

In [4]: interface.read_current_limit()
Out[4]:
array([3.00000001, 3.00000001, 3.00000001, 3.00000001, 3.00000001,
       3.00000001, 3.00000001, 3.00000001, 3.00000001, 3.00000001,
       3.00000001, 3.00000001, 3.00000001, 3.00000001, 3.00000001,
       3.00000001, 3.00000001, 3.00000001])

In [5]: interface.read_temperature_limit()
Out[5]:
array([111.76470637, 111.76470637,  70.        ,  70.        ,
       111.76470637, 111.76470637, 111.76470637, 111.76470637,
       111.76470637, 111.76470637, 111.76470637, 111.76470637,
        65.83333343, 111.76470637, 111.76470637, 111.76470637,
       111.76470637, 111.76470637])

In [6]: interface.send_temperature_limit(80)
Out[6]: b'\x12\x06'

In [7]: interface.read_temperature_limit()
Out[7]:
array([80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
 
 ```

**Pull request merged**
